"use client";

import { useCallback, useState } from "react";
import { Check, RotateCcw, Trash2, UserCheck } from "lucide-react";
import { QrScanner } from "@/components/scanner/qr-scanner";
import { StatusBadge } from "@/components/ui/status-badge";

type StudentResult = { kind: "student"; token: string; fullName: string; studentId: string; yearSection: string | null; groupNumber: string | null; status: string };
type ToolResult = { kind: "tool"; token: string; id: string; assetCode: string; toolName: string; condition: string; status: string };

export function BorrowFlow() {
  const [student, setStudent] = useState<StudentResult | null>(null); const [tools, setTools] = useState<ToolResult[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const resolve = useCallback(async (value: string, kind: "student" | "tool") => { const response = await fetch("/api/scan/resolve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ value, kind }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Code could not be verified."); return result as StudentResult | ToolResult; }, []);
  const scanStudent = useCallback(async (value: string) => { setBusy(true); setError(""); try { const result = await resolve(value, "student") as StudentResult; if (result.status !== "active") throw new Error("This student account is not approved for borrowing."); setStudent(result); setTools([]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Student could not be verified."); } finally { setBusy(false); } }, [resolve]);
  const scanTool = useCallback(async (value: string) => { setBusy(true); setError(""); try { const result = await resolve(value, "tool") as ToolResult; if (tools.some((tool) => tool.token === result.token)) throw new Error(`${result.assetCode} is already in the review list.`); if (result.status !== "available" || result.condition === "damaged") throw new Error(`${result.assetCode} is not available for issue.`); setTools((current) => [...current, result]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Tool could not be verified."); } finally { setBusy(false); } }, [resolve, tools]);
  async function confirm() { if (!student || tools.length === 0) return; setBusy(true); setError(""); try { const response = await fetch("/api/borrow", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ borrowerToken: student.token, toolTokens: tools.map((tool) => tool.token) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Checkout could not be completed."); setSuccess(`Checkout complete. Transaction ${result.transactionId}.`); setStudent(null); setTools([]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Checkout could not be completed."); } finally { setBusy(false); } }
  return <div className="workflow-grid"><section className="workflow-main"><div className="step-strip"><span className={student ? "done" : "active"}>1 <b>Identify student</b></span><span className={student && tools.length === 0 ? "active" : tools.length ? "done" : ""}>2 <b>Scan tools</b></span><span className={tools.length ? "active" : ""}>3 <b>Review & confirm</b></span></div>{success && <div className="notice success"><Check aria-hidden="true" /><span>{success}</span></div>}{error && <div className="notice error" role="alert"><span>{error}</span></div>}{!student ? <QrScanner expected="student" onScan={scanStudent} disabled={busy} /> : <><div className="selected-person"><UserCheck aria-hidden="true" /><div><small>VERIFIED BORROWER</small><strong>{student.fullName}</strong><span>{student.studentId} · {student.yearSection ?? "No section"} · Group {student.groupNumber ?? "—"}</span></div><button className="button button-secondary button-small" type="button" onClick={() => { setStudent(null); setTools([]); }}><RotateCcw aria-hidden="true" />Change</button></div><QrScanner expected="tool" onScan={scanTool} disabled={busy} /></>}</section><aside className="review-panel"><header><h2>ISSUE REVIEW</h2><span>{tools.length} scanned</span></header>{tools.length === 0 ? <p className="review-empty">Scanned tools will appear here before checkout.</p> : <ul className="review-list">{tools.map((tool) => <li key={tool.token}><div><strong>{tool.assetCode}</strong><span>{tool.toolName}</span></div><StatusBadge value={tool.condition} /><button type="button" onClick={() => setTools((current) => current.filter((entry) => entry.token !== tool.token))} aria-label={`Remove ${tool.assetCode}`}><Trash2 aria-hidden="true" /></button></li>)}</ul>}<div className="review-footer"><p>Confirm the borrower and every physical asset before issue.</p><button className="button button-primary" type="button" disabled={!student || tools.length === 0 || busy} onClick={confirm}>{busy ? "Checking…" : `Confirm checkout (${tools.length})`}</button></div></aside></div>;
}
